### ISSUE TITLE
Why exactly is the file first saved to a temp file in the same folder, then renamed?

### ISSUE THREAD

**Issue by felixfbecker** [fs-utils/cp#1]
Just interested.

**Comment by jonathanong** [comment]
if the server crashes, you won't end up with half written files. if you copy the same file twice, you won't run into race conditions (or you shouldn't...)

**Comment by felixfbecker** [comment]
The problem I see with it is, let's say I keep images for entries in my database in a folder. If I want to allow an upload to that folder, I would first write it to `/tmp` anyway for the exact reason you stated (half written files). Once that's finished, I would move it to the real folder. There is no real benefit...
